# Generated by Django 3.2.7 on 2021-09-19 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper', models.IntegerField(default=0)),
                ('lower', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BasicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date_time of sample')),
            ],
        ),
        migrations.CreateModel(
            name='PH',
            fields=[
                ('basicrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basicrecord')),
            ],
            bases=('api.basicrecord',),
        ),
        migrations.CreateModel(
            name='PHRange',
            fields=[
                ('basicrange_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basicrange')),
            ],
            bases=('api.basicrange',),
        ),
        migrations.CreateModel(
            name='RoomTemperature',
            fields=[
                ('basicrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basicrecord')),
                ('cooling_sys', models.BooleanField(default=False)),
            ],
            bases=('api.basicrecord',),
        ),
        migrations.CreateModel(
            name='RoomTemperatureRange',
            fields=[
                ('basicrange_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basicrange')),
            ],
            bases=('api.basicrange',),
        ),
        migrations.CreateModel(
            name='SoilHumidity',
            fields=[
                ('basicrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basicrecord')),
            ],
            bases=('api.basicrecord',),
        ),
        migrations.CreateModel(
            name='SoilHumidityRange',
            fields=[
                ('basicrange_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basicrange')),
            ],
            bases=('api.basicrange',),
        ),
        migrations.CreateModel(
            name='TankElectroconductivity',
            fields=[
                ('basicrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basicrecord')),
            ],
            bases=('api.basicrecord',),
        ),
        migrations.CreateModel(
            name='TankElectroconductivityRange',
            fields=[
                ('basicrange_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basicrange')),
            ],
            bases=('api.basicrange',),
        ),
        migrations.CreateModel(
            name='WaterTank',
            fields=[
                ('basicrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basicrecord')),
            ],
            bases=('api.basicrecord',),
        ),
        migrations.CreateModel(
            name='WaterTankRange',
            fields=[
                ('basicrange_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basicrange')),
            ],
            bases=('api.basicrange',),
        ),
        migrations.CreateModel(
            name='WaterTray',
            fields=[
                ('basicrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basicrecord')),
                ('out_valve', models.BooleanField(default=False)),
                ('in_valve', models.BooleanField(default=False)),
            ],
            bases=('api.basicrecord',),
        ),
        migrations.CreateModel(
            name='WaterTrayRange',
            fields=[
                ('basicrange_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basicrange')),
            ],
            bases=('api.basicrange',),
        ),
    ]
